version: '2'

services:
   devcontainer:
     container_name: developmentcontainer
     build:
       context: .
     volumes:
       - ./data/xdev:/xdev
     restart: unless-stopped
     command: tail -F anything
     ports:
           - "18000:80"
           - "22222:22"
           - "5000:5000"
     environment:
       - TEST_VAR=Dies ist ein Test
   mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - ./data/mysql:/var/lib/mysql
